"""initial schema

Revision ID: 93710e3f6167
Revises: 
Create Date: 2026-05-01 03:27:04.188820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93710e3f6167'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("algorithm IN ('dqn', 'collab_filter', 'popularity_baseline')", name='ck_model_registry_algorithm'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index('ix_model_registry_active', 'model_registry', ['algorithm'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_asin'), 'products', ['asin'], unique=True)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index('ix_products_category_rating', 'products', ['category', 'avg_rating'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cart_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('recommendation_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('add', 'remove', 'update_quantity')", name='ck_cart_events_action'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_events_occurred_at'), 'cart_events', ['occurred_at'], unique=False)
    op.create_index('ix_cart_events_recommendation_context', 'cart_events', ['recommendation_context'], unique=False, postgresql_using='gin')
    op.create_index('ix_cart_events_user_action_time', 'cart_events', ['user_id', 'action', 'occurred_at'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('view', 'click', 'search', 'category_browse')", name='ck_interactions_event_type'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_occurred_at'), 'interactions', ['occurred_at'], unique=False)
    op.create_index('ix_interactions_session', 'interactions', ['session_id', 'occurred_at'], unique=False)
    op.create_index('ix_interactions_user_time', 'interactions', ['user_id', 'occurred_at'], unique=False)
    op.create_table('model_episodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('next_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_episodes_model_time', 'model_episodes', ['model_id', 'recorded_at'], unique=False)
    op.create_index('ix_episodes_recorded_at', 'model_episodes', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_episodes_recorded_at', table_name='model_episodes')
    op.drop_index('ix_episodes_model_time', table_name='model_episodes')
    op.drop_table('model_episodes')
    op.drop_index('ix_interactions_user_time', table_name='interactions')
    op.drop_index('ix_interactions_session', table_name='interactions')
    op.drop_index(op.f('ix_interactions_occurred_at'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index('ix_cart_events_user_action_time', table_name='cart_events')
    op.drop_index('ix_cart_events_recommendation_context', table_name='cart_events', postgresql_using='gin')
    op.drop_index(op.f('ix_cart_events_occurred_at'), table_name='cart_events')
    op.drop_table('cart_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_products_category_rating', table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_asin'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_model_registry_active', table_name='model_registry', postgresql_where=sa.text('is_active = true'))
    op.drop_table('model_registry')
    # ### end Alembic commands ###
